name: Build
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  matrix-build:
    name: Matrix Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc: [dmd-latest, ldc-1.34.0]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        run: dub test --build=unittest-cov

      - name: Run tests (dip1000)
        env:
          DFLAGS: -dip1000
        run: dub test --build=unittest-cov

      - name: Run tests (in)
        env:
          DFLAGS: -preview=in
        run: dub test --build=unittest-cov

      - name: Run tests (dip1000 & in)
        env:
          DFLAGS: -dip1000 -preview=in
        run: dub test --build=unittest-cov

      - name: Build examples
        run: dub --root examples build --parallel

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
